version: '3.9'
services:
  db:
    container_name: postgres
    image: postgres:15.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: icecreamshopdb
    ports:
      - 5432:5432
    volumes:
      - ./db-postgres/db:/var/lib/postgresql/data
      - ./db-postgres/import:/import
    networks:
      - eshop

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - eshop

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - eshop

  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:5.0.13
    networks:
      - eshop
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - eshop
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:5.0
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - eshop
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

  storage:
    image: jaegertracing/all-in-one:1.22
    container_name: jaegertracing
    ports:
      # Agent zipkin.thrift compact
      - 5775:5775/udp
      # Agent jaeger.thrift compact
      - 6831:6831/udp
      # Agent jaeger.thrift binary
      - 6832:6832/udp
      # Agent config HTTP
      - 5778:5778
      # Collector HTTP
      - 14268:14268
      # Collector gRPC
      - 14250:14250
      # Web HTTP
      - 16686:16686
    networks:
      - eshop
  inventory:
    image: quarkus/altera-shop-inventory
    container_name: altera-shop-inventory
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db/icecreamshopdb
      QUARKUS_LOG_HANDLER_GELF_HOST: graylog
      KAFKA_SERVER: kafka:29092
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS: localhost:29092
      QUARKUS_KAFKA_STREAMS_APPLICATION_SERVER: localhost:9999
    ports:
      - 8081:8081
    depends_on:
      - db
      - kafka
      - graylog
    networks:
      - eshop

  store:
    image: quarkus/altera-shop-store
    container_name: altera-shop-store
    environment:
        QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db/icecreamshopdb
        QUARKUS_LOG_HANDLER_GELF_HOST: greylog
        INVENTORY_URL: http://inventory:8081
        KAFKA_SERVER: kafka:29092
        KAFKA_BOOTSTRAP_SERVERS: kafka:29092
        QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS: localhost:29092
        QUARKUS_KAFKA_STREAMS_APPLICATION_SERVER: localhost:9999

    ports:
      - 8080:8080
    depends_on:
      - db
      - kafka
      - graylog
    networks:
      - eshop

networks:
  eshop:
    name: quarkus-icrecrem-shop-network
    driver: bridge

