version: '3.9'
services:       
   backend:
      image: juankprada/icecream-shop:latest
      ports:
         - 8080:8080
      networks:
         - eshop
         
networks:
   eshop:
      name: quarkus-icrecrem-shop-network