version: '3.9'
services:
  db:
    container_name: postgres
    image: postgres:15.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: icecreamshopdb
    ports:
      - 5432:5432
    volumes:
      - ./db-postgres/db:/var/lib/postgresql/data
      - ./db-postgres/import:/import
    networks:
      - postgres
networks:
  postgres:
    driver: bridge

