version: '3.9'

services:
  storage:
    image: jaegertracing/all-in-one:1.22
    container_name: jaegertracing
    ports:
      # Agent zipkin.thrift compact
      - 5775:5775/udp
      # Agent jaeger.thrift compact
      - 6831:6831/udp
      # Agent jaeger.thrift binary
      - 6832:6832/udp
      # Agent config HTTP
      - 5778:5778
      # Collector HTTP
      - 14268:14268
      # Collector gRPC
      - 14250:14250
      # Web HTTP
      - 16686:16686